EMBEDDER_MODEL: "all-MiniLM-L6-v2"
VECTOR_DB_COLLECTION_NAME: "pdf_collection_test"
LLM_BACKEND: "ollama"
LLM_MODEL: "llama3"
GEMINI_API_KEY: ""
DOCS_DIR: "tests/docs"
VECTOR_DB_DIR: "tests/vector_db"
